### ISSUE TITLE
Add sorting to the output

### ISSUE THREAD

**Issue by Scoty** [ORESoftware/fame#4]
I would like to be able to sort the table output by any of the columns.

**Comment by ORESoftware** [comment]
ahh nice, let me work on it

**Comment by ORESoftware** [comment]
so I think the best way to do this would be:

`--sort='files modified,author'

or just use numbers for the columns, not sure

**Comment by ORESoftware** [comment]
Alright so in this patch I added sorting: `fame@0.0.111`

the readme was updated and says:

You can sort using the --sort and --order options. For example:

```bash

fame --sort=1 --order=asc  # will sort by the the 2nd column, ascending
fame --sort=2,3 --order=desc  # will sort by the the 3rd and 4th column

```

Or for example, instead of numbers you can also just use the name of the column:

```bash

fame --sort='added lines, files modified' --order=asc

```

let me know if it works for you.
