### ISSUE TITLE
show names instead of email addresses

### ISSUE THREAD

**Issue by tessus** [ORESoftware/fame#5]
I really like your tool. It's very fast.

The only thing I'm missing is to see the authors' names instead of the email addresses.
Any chance you could add an option for that?

**Comment by tessus** [comment]
And btw, just out of curiosity, what's up with the commit messages? I have never seen more useless messages. Is there an error in the commit process or are they used to obfuscate what is actually happening? I'm really puzzled by this.

**Comment by ORESoftware** [comment]
A lot of the commit messages are just default commit messages from a git tool I have. I will probably squash a lot of the commits that have bogus commit messages some day.

the email address was the unique thing to distinguish a user, it's possible the same user with the same name made commits to the project from two (or three or four) different email addresses, so that's why it was designed that way.  

I can add the name, maybe as the first column, and the email address as the second column?

The only problem is it's not easy to merge users even if they have the same name, for example, I might have one account with "Alex Mills" and another with "Alexander Mills" etc..email addresses are unique so it's good to use that as the primary key.

**Comment by tessus** [comment]
Thanks for the reply.

> I can add the name, maybe as the first column, and the email address as the second column?

Yes, this approach would probably be even better.

> The only problem is it's not easy to merge users even if they have the same name, for example, I might have one account with "Alex Mills" and another with "Alexander Mills" etc..email addresses are unique so it's good to use that as the primary key.

Merging users is a completely different problem and would be the next step IMO. The thing is a user could use (1) different names but the same email address (as you've already mentioned), but a user could also use (2) the same name and different email addresses. And - even worse, both of these possibilities could occur at the same time (3).

There's no useeful way to automate this (except for case 1). The tool would have to allow a user to specify which names and email addresses belong to the same person.

**Comment by ORESoftware** [comment]
yeah I guess it would be something like:

some file named '.fame.js' :

```js

exports.default = {

  "display names": {

     "Alex Mills": {
       emails: [ 'alex@oresoftware.com', 'alexander.d.mills@gmail.com']
     },

     "Helmut Tessug": {
      emails: ['helmet@tessug.com', 'tessus@github.com']
    }

 }

}
```

and it would display the name instead of the email, in this case? and aggregate the results by the display name.


I think that's all that would be necessary, as far as I can tell

**Comment by ORESoftware** [comment]
The problem of course is for new emails that get introduced to the repo that aren't in the config, in that case, it would just show their email address.

**Comment by tessus** [comment]
> and it would display the name instead of the email, in this case? and aggregate the results by the display name

In case of merging, I'd say yes. Otherwise it could make sense to show both (name and email).

> The problem of course is for new emails that get introduced to the repo that aren't in the config, in that case, it would just show their email address.

I think that's fine too, because it will show the user that they have to update the file.

One question though: what would happen, if there were no entry for a user at all in `.fame.js`?
In that case name and email should be shown, shouldn't it? What do you think?

**Comment by tessus** [comment]
I just wanted to follow up. What is the status?

**Comment by ORESoftware** [comment]
Havent made changes yet, but I think I know how to proceed, will work on it this weekend and ping you when its ready, thanks

**Comment by tessus** [comment]
Great, thanks for the info.

**Comment by ORESoftware** [comment]
@tessus 

alright, if you can test the feature, that'd be good..try this:

```bash
git clone https://github.com/ORESoftware/fame.git
cd fame
git checkout author_conf  # check out the feature branch
npm install -g .
```

and then configure your conf file like this:

```bash

mkdir -p ~/.fame

cat <<EOF > ~/.fame/fame.conf.js

'use strict';

exports.default = {

  'display names': {

     'John James': {
        emails: ['jj@watt.com', 'abc@example.com', 'john@james-mac.local']
     },

    'Thurgood Marshall': {
        emails: ['tm@supremecourt.us', 'marsh@spc.gov']
     },

     'Alexander Mills': {
      emails: ['alex@oresoftware.com', 'alex@alexs-mac.local']
     }
  }

}

EOF
```

put your info in there, instead of the dummy data

let me know if it works for you, maybe we can discuss how to make it a more streamlined process to configure things for most users.

**Comment by ORESoftware** [comment]
the author_conf branch also solves this problem https://github.com/ORESoftware/fame/issues/6

**Comment by tessus** [comment]
Awesome, I will test this later tonight.

As auggestion for the config file: Lose everything, but the actual data:

```
{

  'display names': {

     'John James': {
        emails: ['jj@watt.com', 'abc@example.com', 'john@james-mac.local']
     },

    'Thurgood Marshall': {
        emails: ['tm@supremecourt.us', 'marsh@spc.gov']
     },

     'Alexander Mills': {
      emails: ['alex@oresoftware.com', 'alex@alexs-mac.local']
     }

  }

}
```

**Comment by ORESoftware** [comment]
generally I prefer .js instead of .json since you can add comments to .js etc

**Comment by tessus** [comment]
Ah, I see. For me it's a config file. The input can be parsed and if it's not valid an error message can be thrown. If somebody fucks up the code in your file, e.g uses `exports.defaukt`, the entire program stops working.
But I don't really care as long as it does its job. I'm very happy that you added this feature.
I'll test it later tonight.

**Comment by tessus** [comment]
oh, is there also an option to show the name and email address? and what is supposed to happen, if there's no name specified for an email address? I guess I will find out later. ;-)

**Comment by ORESoftware** [comment]
Just 1 column for the user name or email.
if there is no corresponding name for the email address, then the email address shows up.

**Comment by tessus** [comment]
> $ npm install -g .

This did not work, but I was able to install it locally within the repo and used this version to do the tests.
The name replacement works. 👍 

> the author_conf branch also solves this problem

Nope, not for me. I added the following to the config file:

```
     'Andres Gomez Casanova': {
      emails: ['angoca@yahoo.com', 'angoca at yahoo or gmail']
     },
```

But it still does not show all commits:

```
$ ~/work/fame/cli/fame.js
fame: SHA/Branch: HEAD
fame: Files must match at least one of: [ /.*/ ]
fame: Full branch name: master
fame: processing commit no.: 101, finished: 98.06%

  ┌────────────────────────────────┬────────────────┬─────────────┬─────────────┬───────────────┬────────────────────┬─────────────────┐
  │            Author              │ Files Modified │ Commits     │ Added Lines │ Removed Lines │ Total Line Changes │ Net Lines Added │
  ├────────────────────────────────┼────────────────┼─────────────┼─────────────┼───────────────┼────────────────────┼─────────────────┤
  │ Helmut K. C. Tessarek          │ 40 / 97.56%    │ 99 / 96.12% │ 5020        │ 1115          │ 6135               │ 3905            │
  ├────────────────────────────────┼────────────────┼─────────────┼─────────────┼───────────────┼────────────────────┼─────────────────┤
  │ Andres Gomez Casanova          │ 5 / 12.20%     │ 2 / 1.94%   │ 962         │ 29            │ 991                │ 933             │
  └────────────────────────────────┴────────────────┴─────────────┴─────────────┴───────────────┴────────────────────┴─────────────────┘
```

> maybe we can discuss how to make it a more streamlined process to configure things for most users.

I was thinking about writing a bash or python script that creates or better said modifies the config file by scanning the current repo. Something that makes use of `git log --pretty="%an | %ae" |sort -u`.
Unfortunately the config file is not valid json, so I can't parse it or use jq to modify it. Anyway, my scan approach has a caveat anyway. If there are 2 names with the same email address, you would be stuck with the last entry.
Well, I could write a js script, but I suck in coding js.

**Comment by ORESoftware** [comment]
let me test if on your repo, I didn't try that yet

**Comment by ORESoftware** [comment]
ah, it was an obvious bug, now it should work, try:

```
npm i -g fame@0.0.117-rc.1
```

**Comment by ORESoftware** [comment]
WRT to updating the config, we could do something like this:

```
fame --add  <display-name> <email>
```

and it would create the configuration file if it didn't exist

**Comment by tessus** [comment]
> `npm i -g fame@0.0.117-rc.1`

Eureka! It works with this version.

> `fame --add  <display-name> <email>`
> and it would create the configuration file if it didn't exist

Such a command would be awesome.

But your statement is not clear to me. The config file would exist after only one invocation of this command.
Or do you mean the command would either add an entry or modify an entry in the config file, if the name didn't exist or the name existed and a new email address didn't exist for that name?
Because it should be perfectly valid to do this:

```
fame --add  "Helmut K. C. Tessarek" "tessarek@evermeet.cx"
fame --add  "Helmut K. C. Tessarek" "tessarek@ca.ibm.com"
fame --add  "Helmut K. C. Tessarek" "kt107v@intl.att.com"
```

However, what would happen, if one were to do this after using the above 3 commands:

```
fame --add  "K. C. Tessarek" "tessarek@evermeet.cx"
```

So maybe there should be a guard or error message that one cannot add another name with an already registered email address.

What do you think?

**Comment by tessus** [comment]
Oh, I thought that fame would sort by commits by default, but the output of fame seems random, if I just use `fame` w/o arguments.

**Comment by ORESoftware** [comment]
it uses git log, git log output should be sorted by date..but it's the order of committers.
I could sort it by default by the number of commits, that would be easy to do.

**Comment by tessus** [comment]
I'm not saying you should. I just thought it was and that the change broke the default. But if it never was, then never mind.
I like it as the defaulr, but other might like another one better.
No worries, all good. I can use an alias. I just wanted to make sure that the change didn't break anything.

**Comment by ORESoftware** [comment]
ok, so you're right .js was too hard to manipulate programmatically, so I changed it to .json

```
npm i -g fame@0.0.117-rc.2
```

now you can create the config file and add an email using

```bash
fame --add <email> <user>
```

**Comment by tessus** [comment]
Hmm, ok, the following command does not work:

`fame --add "angoca at yahoo or gmail" "Andres Gomez Casanova" --ignore-email-warning`
or
`fame --ignore-email-warning --add "angoca at yahoo or gmail" "Andres Gomez Casanova"`

I added it manually and the code still works. 

Any reason, why you changed `fame --add <display-name> <email>` to `fame --add <email> <user>`?
This makes it harder to add a user with several email addresses. You have to replace stuff within the last command instead of just deleting the email address at the end.

**Comment by ORESoftware** [comment]
yeah let me change it to:

```
fame --add <user> -e email1 -e email2 -e email3

```

will do that tomorrow

**Comment by tessus** [comment]
No worries, no rush. Btw, `fame --add <user> <email>` would already be an improvement. If you don't want to add multiple arguments that's fine too. Ttyl.

**Comment by tessus** [comment]
Oh, sorry. Not sure why this is still open.

Thanks for the feature.
