### ISSUE TITLE
Question: what's the meaning of net lines added

### ISSUE THREAD

**Issue by Akimotorakiyu** [ORESoftware/fame#9]
## Question: what's the meaning of net lines added

![图片](https://user-images.githubusercontent.com/31165554/69163858-f0d0c580-0b29-11ea-8a35-d7c23b5dada1.png)

**Comment by ORESoftware** [comment]
net lines added = lines added - lines removed

it assumes that if a developer deletes lines of code, it's still an added value, so that's why "removed lines" is shown separately

**Comment by Akimotorakiyu** [comment]
thank you.
